### ISSUE TITLE
Some math not rendering properly

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-demo-site#18]
https://iev-staging.geolexica.org/concepts/103-03-05/

<img width="994" alt="Screen Shot 2020-04-15 at 2 55 53 AM" src="https://user-images.githubusercontent.com/11865/79262940-9fecaf80-7ec4-11ea-9ae5-b416605c2d06.png">

But the French version renders right:
<img width="936" alt="Screen Shot 2020-04-15 at 2 56 08 AM" src="https://user-images.githubusercontent.com/11865/79262960-a844ea80-7ec4-11ea-9bef-51610a17211d.png">

I can't figure out the difference in encoding method between them:
```yaml
eng:
  id: 1030305
  terms:
  - type: expression
    normativeStatus: preferred
    designation: Dirac function
  - type: expression
    normativeStatus: preferred
    designation: Dirac delta function
  - type: expression
    normativeStatus: preferred
    designation: unit pulse
  - type: expression
    normativeStatus: preferred
    designation: unit impulse
    geographicalArea: US
  - type: symbol
    designation: δ
    international: true
  definition: "{{distribution, IEV:103-01-03}} assigning to any function stem:[f](stem:[x]),
    continuous for stem:[x = 0], the value stem:[f](0)"
  language_code: eng
  notes:
  - The Dirac function can be considered as the limit of a function, equal to zero
    outside a small interval containing the origin, and the integral of which remains
    equal to unity when this interval tends to zero. See Figure 2, where instead of
    a triangle any other shape with area 1 is possible, too.
  - The Dirac function is the derivative of the unit step function considered as a
    distribution.
  - |-
    The Dirac function can be defined for any value stem:[x]<sub>0</sub> of the variable stem:[x]. The usual notation is:

    stem:[f ( x_0 ) = ∫_(   - oo)^(   + oo) delta ( x - x_0 ) f ( x ) d x]

    image::/assets/images/parts/103/103-03-053.png[Figure 1 - Distribution de Dirac; Dirac function]
  examples: []
  entry_status: Standard
  classification: Preferred
  date_accepted: '2009-12-01T00:00:00+00:00'
  date_amended: '2009-12-01T00:00:00+00:00'
  review_date: '2009-12-01T00:00:00+00:00'
  review_decision_date: '2009-12-01T00:00:00+00:00'
  review_decision_event: published
fra:
  id: 1030305
  terms:
  - type: expression
    normativeStatus: preferred
    designation: distribution de Dirac
    gender: f
    plurality: singular
  - type: expression
    normativeStatus: preferred
    designation: impulsion unité
    gender: f
    plurality: singular
  - type: expression
    normativeStatus: preferred
    designation: percussion unité
    gender: f
    plurality: singular
  definition: "{{distribution, IEV:103-01-03}} associant à toute fonction stem:[f](stem:[x]),
    continue pour stem:[x = 0], la valeur stem:[f](0)"
  language_code: fra
  notes:
  - La distribution de Dirac peut être considérée comme la limite d'une fonction nulle
    en dehors d'un petit intervalle contenant l'origine et dont l'intégrale reste
    égale à l'unité lorsque cet intervalle tend vers zéro. Voir la Figure 2, où le
    triangle peut être remplacé par n’importe quelle forme d’aire unité.
  - La distribution de Dirac est la dérivée de la fonction échelon unité considérée
    comme une distribution.
  - |-
    La distribution de Dirac peut être définie pour toute valeur stem:[x]<sub>0</sub> de la variable stem:[x]. La notation usuelle est:

    stem:[f ( x_0 ) = ∫_(   - oo)^(   + oo) delta ( x - x_0 ) f ( x ) d x]
  examples: []
  entry_status: Standard
  classification: Preferred
  review_decision_event: published
```
