### ISSUE TITLE
CI script is clearly broken

### ISSUE THREAD

**Issue by skalee** [glossarist/iev-demo-site#26]
Builds for branches are failing. GitHub workflow is failing on action:

```yaml
      - name: Setup git submodules (authenticated)
        env:
          MLGT_DATA_DEPLOY_KEY: ${{ secrets.GEOLEXICA_DATABASE_DEPLOY_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MLGT_DATA_DEPLOY_KEY}"
          make update-init update-modules
```

Which is probably some leftover.
