### ISSUE TITLE
Please clarify how to display concept source

### ISSUE THREAD

**Issue by skalee** [glossarist/iev-demo-site#63]
Please clarify how to display concept's authoritative source on IEV site.

There are two places where authoritative source appears: the non-localized part (the upper one on picture below) and the localized one. They are defined in a quite different ways.

| ![Zrzut ekranu 2020-11-06 o 12 13 25](https://user-images.githubusercontent.com/154287/98360350-f15bb800-2029-11eb-9dc8-709b928bc023.png)
|-

### The upper (non-localized) one

The upper one is displayed with following piece of code, where `part_number` is the first segment of term ID, i.e. 112 in this case, as requested in #4.

https://github.com/glossarist/iev-demo-site/blob/fc31fd57732c6ab16b61fe5bf2012f7e02342821/_source/_includes/concept-source.html#L2-L7

Note that "IEC 60050-" part is fixed and cannot be overridden (I'm not sure if that's a problem though).

### The lower (localized) one

The lower one is displayed with a following piece of code:

https://github.com/glossarist/iev-demo-site/blob/fc31fd57732c6ab16b61fe5bf2012f7e02342821/_source/_includes/localized-concept.html#L28-L42

It relies on a hash composed of `ref`, `clause` and `link` entries similarly to the other Geolexica sites. It is displayed only if `authoritative_source.ref` in given translation is different than in `eng` translation (note that one of them may be null).

### Question

I'm quite surprised that concept "main" source works differently than translation source. @ronaldtse Please confirm that this is how it should be.

### Concept source

The screenshot was taken from concept [112-01-32](https://iev-staging.geolexica.org/concepts/112-01-32/) defined as follows (some portions omitted):

```yaml
---
termid: 1120132
term: unit equation

eng:
  id: 1120132
  terms:
  - type: expression
    normative_status: preferred
    designation: unit equation
  definition: mathematical relation between base units, coherent derived units or
    other units of measurement
  language_code: eng
  notes:
  - "(...)"
  examples: []
  entry_status: Standard
  authoritative_source:
    ref: ISO/IEC GUIDE 99:2007  MOD
    clause: ISO/IEC GUIDE 99:2007 1.23 MOD
    link: https://www.iso.org/standard/45324.html
  date_accepted: '2010-01-01T00:00:00+00:00'
  date_amended: '2010-01-01T00:00:00+00:00'
  review_date: '2010-01-01T00:00:00+00:00'
  review_decision_date: '2010-01-01T00:00:00+00:00'
  review_decision_event: published
fra:
  id: 1120132
  terms:
  - type: expression
    normative_status: preferred
    designation: équation aux unités
    gender: f
    plurality: singular
  definition: relation d'égalité entre des unités de base, des unités dérivées cohérentes
    ou d'autres unités de mesure
  language_code: fra
  notes:
  - "(...)"
  examples: []
  entry_status: Standard
  authoritative_source:
    ref: ISO/IEC GUIDE 99:2007
    clause: '1.23'
    link: https://www.iso.org/standard/45324.html
  date_accepted: '2010-01-01T00:00:00+00:00'
  date_amended: '2010-01-01T00:00:00+00:00'
  review_date: '2010-01-01T00:00:00+00:00'
  review_decision_date: '2010-01-01T00:00:00+00:00'
  review_decision_event: published
```
